config/routes.rb
Rails.application.routes.draw do
root to: 'boards#index'
resources :travels, only: :index
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/boards_controller.rb
class BoardsController < ApplicationController

  def index
  end
  
end

app/controllers/travels_controller.rb
class TravelsController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/boards_helper.rb
module BoardsHelper
end

app/helpers/travels_helper.rb
module TravelsHelper
end

app/views/boards/_header.html.erb
<div class="header">
  <div class="header-box">
    <div class="work">
      <div class="work-lists" id="worklists">work
      </div>
    </div>

    <div class="travel">
      <div class="travel-lists" id="travellists">
        <%= link_to 'travel', travels_path %>
      </div>
    </div>
    <div class="food">
    food
    </div>
    <div class="life">
    life
    </div>
  </div>
</div>

app/views/boards/index.html.erb
<%= render "header" %>
<div class="wrapper">
  <div class="profile-box">
    <div class="profile-text">
      <h1>Profile</h1>
      <h3>田野倉 豪希 (たのくら つよき)</h3>
      <p>1988年11月24日生まれ、東京育ち</p>
      <p>2013年、青山学院大学理工学部を卒業後</p>
      <p>海外へ旅立つ、フィリピンでの語学留学、</p>
      <p>ワーキングホリデーでオーストラリア、タイにてスキューバダイビングのガイドなどを経験、合計約4年の海外生活後、</p>
      <p>2019年8月に帰国。</p>
      <p>居酒屋の新規立ち上げに携わるなど、チャレンジを好む性格。</p>
      <p>趣味ではサーフィン、スノーボード、ダイビング、釣り、写真など自然と関われることが大好き。</p>
    </div>

    <div class="profile-photo">
    </div>
  </div>
  <div class="fixed-background background-1">
  <h1>WORK</h1>
  </div>
  <div class="scroll-background background-color-1">
    <h2>Programming</h2>
    <p>2020年末からプログラミング学習を始めてからの製作物。</p>
    <p>Ruby、JavaScriptなどで作成。</p>
    <p>現在もRuby on Railsを用いてオリジナルアプリケーションの作成中。</p>
    <p>また、Pythonも独学で学習しており、常に新しいことにチャレンジ。</p>

    <h2>photography</h2>
    <p>風景写真を主に撮り続けている。</p>
    <p>夕景や星景写真を好む。</p>
    <p>数多くある中、自ら厳選。</p>
  </div>
  <div class="fixed-background background-2">
    <h1>TRAVEL</h1>
  </div>
  <div class="scroll-background background-color-2">
    <h1></h1>
  <br><%= link_to 'i have been to some country', travels_path %>
   <p>約4年間撮りためた写真たち。</p>
   <p>数々の思い出があり、とても大事な記録と記憶。</p>
   <p>経験は宝だと思えるきっかけになった旅。</p>
  </div>
  <div class="fixed-background background-1">
    <h1>FOOD</h1>
  </div>
  <div class="scroll-background background-color-1">
    <p>飲食店にて勤務していたこともあり、食事には気を使うようになる。</p>
    <p>現在は、作れるものはなるべく自分で作ることを大事にしている。</p>
    <p>保存料や化学調味料など、なるべく摂取しない生活を目指す。</p>
    <p>味噌を始め、キムチ、ぬか漬けなど発酵食品に関心があり、ワークショップも積極的に受講。</p>
    <p>オーストラリアで出会った健康ドリンク、KOMBUCHAも新メニューとして居酒屋で提供。</p>
    <p>最近は辛いものが好き。</p>
  </div>
  <div class="fixed-background background-2">
    <h1>LIFE</h1>
  </div>
  <div class="scroll-background background-color-2">
    <h1></h1>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Portfolio</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/travels/index.html.erb
<div class="header-index">
  <div class="header-box">
    <div class="australia" id="aus">
      <a href="#tabpage1">australia</a>
    </div>
    <div class="thailand">
      thailand
    </div>
    <div class="indonesia">
      indonesia
    </div>
    <div class="malaysia">
      malaysia
    </div>
    <div class="philippines">
      philippines
    </div>
    <div class="vietnam">
      vietnam
    </div>
    <div class="cambodia">
      cambodia
    </div>
    <div class="laos">
      laos
    </div>
  </div>
</div>

<div class="travel-body">
  <div class="travel-wrapper">
    <div class="travel-text-box">
      <div class="travel-text-title">
        <h1>travel</h1>
        <p>約4年間に及ぶ海外生活</p>
        <p>数多の思い出が...</p>
      </div> 
    </div>
    <div class="insta">
      <!-- SnapWidget -->
     <iframe src="https://snapwidget.com/embed/923546" class="snapwidget-widget" allowtransparency="true" frameborder="0" scrolling="no" style="border:none; overflow:hidden;  width:495px; height:495px"></iframe>
    </div>
  </div>
</div>